  (use-modules
             (gnu packages bash)
             (gnu packages admin)
 (guix licenses)
 ((guix licenses) #:prefix license:)
 (guix packages)
 (guix download)
 (guix gexp)
 (guix git-download)
 (guix build-system asdf)
 (guix build-system cmake)
 (guix build-system copy)
 (guix build-system gnu)
 (guix build-system haskell)
 (guix build-system meson)
 (guix build-system perl)
 (guix build-system python)
 (guix build-system trivial)
 (guix utils)
   (gnu packages autotools)
 (gnu packages base)
 (gnu packages bison)
 (gnu packages build-tools)
 (gnu packages calendar)
 (gnu packages check)
 (gnu packages datastructures)
 (gnu packages docbook)
 (gnu packages documentation)
 (gnu packages fontutils)
 (gnu packages freedesktop)
 (gnu packages fribidi)
 (gnu packages gawk)
 (gnu packages gl)
 (gnu packages glib)
 (gnu packages gperf)
 (gnu packages gtk)
 (gnu packages gnome)
 (gnu packages haskell-check)
 (gnu packages haskell-web)
 (gnu packages haskell-xyz)
 (gnu packages image)
 (gnu packages imagemagick)
 (gnu packages libevent)
 (gnu packages libffi)
 (gnu packages linux)
 (gnu packages lisp-check)
 (gnu packages lisp-xyz)
 (gnu packages logging)
 (gnu packages lua)
 (gnu packages m4)
 (gnu packages man)
 (gnu packages maths)
 (gnu packages mpd)
 (gnu packages pcre)
 (gnu packages perl)
 (gnu packages pkg-config)
 (gnu packages pretty-print)
 (gnu packages pulseaudio)
 (gnu packages python)
 (gnu packages python-build)
 (gnu packages python-crypto)
 (gnu packages python-xyz)
 (gnu packages readline)
 (gnu packages serialization)
 (gnu packages sphinx)
 (gnu packages suckless)
 (gnu packages texinfo)
 (gnu packages textutils)
 (gnu packages time)
 (gnu packages video)
 (gnu packages web)
 (gnu packages xdisorg)
 (gnu packages xml)
 (gnu packages xorg)
 (gnu packages wm)
             )
  
  (package
    (name "hollow")
    (version "1")
    (source
     (origin
       (method git-fetch)
       (uri (git-reference
             (url "https://github.com/m4lin/hollow")
             (commit version)))
       (file-name (git-file-name name version))
       (sha256
        (base32 "02i0wrdxn1fnpabpns4sznk3h8zck14gk6zingv02nfpaa5dlw1j"))))
    (build-system gnu-build-system)
    (inputs
     (list libx11))
    (arguments
     `(#:tests? #f                      ;no tests
       #:phases
       (modify-phases %standard-phases
         (delete 'configure))           ;no configure script
       #:make-flags
       (list (string-append "CC=" ,(cc-for-target))
             (string-append "BIN_DIR=" %output "/bin"))))
    (home-page "https://github.com/m4lin/hollow")
    (synopsis " hollow here ")
    (description
     "@command{hollow} hollow here too.")
    (license license:gpl2))
